# Generated by Django 3.2.1 on 2021-05-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='full_name',
        ),
    ]
