# Generated by Django 3.2.1 on 2021-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_rename_name_person_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='task',
        ),
        migrations.AddField(
            model_name='machine',
            name='task',
            field=models.ManyToManyField(null=True, to='MainApp.Task'),
        ),
    ]
