# Generated by Django 3.2.1 on 2021-05-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20210508_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='task',
            field=models.ManyToManyField(to='MainApp.Task'),
        ),
    ]
