# Generated by Django 3.2.1 on 2021-05-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_rename_name_machine_machine_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='machine',
            field=models.ManyToManyField(related_name='machine', to='MainApp.Machine'),
        ),
    ]
