# Generated by Django 3.2.2 on 2021-05-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20210508_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
