# Generated by Django 3.2.2 on 2021-05-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20210512_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.ImageField(null=True, upload_to='ControlYourInvestment/images/'),
        ),
    ]
