# Generated by Django 3.2.2 on 2021-05-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_alter_task_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
