# Generated by Django 3.2.2 on 2021-05-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_taskimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='picture',
        ),
    ]
