# Generated by Django 3.2.2 on 2021-05-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_auto_20210514_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='task',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.task'),
        ),
    ]
