# Generated by Django 3.2.2 on 2021-05-18 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='upload',
        ),
    ]
